<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>Cavern712</AssemblyName>
    <RootNamespace>Cavern712</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\third_party\Cavern\Cavern.Format\Cavern.Format.csproj" />
  </ItemGroup>
</Project>
